apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: devops-project
  namespace: argocd
spec:
  description: DevOps Mini Project

  sourceRepos:
    - https://github.com/your-username/react-devops-app.git
    - '*'

  destinations:
    - namespace: devops-project
      server: https://kubernetes.default.svc
    - namespace: argocd
      server: https://kubernetes.default.svc

  clusterResourceWhitelist:
    - group: '*'
      kind: '*'

  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'

  orphanedResources:
    warn: true
